### ISSUE TITLE
Add an MP: Kieran Mullen

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#10]
### Name of the MP

Kieran Mullan

### What is the MPs political party?

Conservative

### Constituency

Bexhill and Battle

### Name of source

Pink News

### URL of source

https://www.thepinknews.com/2019/12/13/uk-gay-parliament-world-2019-general-election-snp-conservatives-labour-lgbt/

### Explanation of source

According the UK LGBT Website Pink News, he is openly LGBT+

**Comment by johnpeart** [comment]
Thank you.

Another contributor has rightly pointed out that Kieran Mullan has simply moved constituencies; he was previously in the dataset with a public source. This will be updated later today.
