### ISSUE TITLE
Add an MP: Alan Gemmell

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#11]
### Name of the MP

Alan Gemmell

### What is the MPs political party?

Labour

### Constituency

Central Ayrshire

### Name of source

Irvine Times

### URL of source

https://www.irvinetimes.com/news/14183179.irvines-alan-gemmell-receives-obe-in-queens-new-years-honours/

### Explanation of source

He is openly gay and has a husband

**Comment by johnpeart** [comment]
Thank you!

I'll add to the dataset later on today.
