### ISSUE TITLE
Add an MP: Andrew Pakes

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#12]
### Name of the MP

Andrew Pakes

### What is the MPs political party?

Labour

### Constituency

Peterborough

### Name of source

Attitude Magazine

### URL of source

https://www.attitude.co.uk/news/lgbtq-mps-2024-election-469308/

### Explanation of source

Openly gay

**Comment by johnpeart** [comment]
Thank you!

I'll add to the dataset later on today.
