### ISSUE TITLE
Add an MP: Adam Dance

### ISSUE THREAD

**Issue by keywoodcharlie** [johnpeart/lgbt-mp#13]
### Name of the MP

Adam Dance

### What is the MPs political party?

Liberal Democrat

### Constituency

Yeovil

### Parliamentary website

https://members.parliament.uk/member/5191/contact

### Name of source

Local Government Association

### URL of source

https://www.local.gov.uk/sites/default/files/documents/7.56_District_Councils_BAC_02_1.pdf

### Explanation of source

Page 9 of the document is a personal statement, written by Adam Dance. Underneath, there is a ticked checkbox next to which says 'LGBT community member.'

**Comment by johnpeart** [comment]
Thank you. This has now been included in the dataset.
