### ISSUE TITLE
Add an MP: Adam Dance

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#14]
### Name of the MP

Adam Dance

### What is the MPs political party?

Liberal Democrat

### Constituency

Yeovil

### Name of source

Local Government documment

### URL of source

https://www.local.gov.uk/sites/default/files/documents/7.56_District_Councils_BAC_02_1.pdf

### Explanation of source

Local Government document identifies him as LGBT

**Comment by johnpeart** [comment]
Thank you. This has now been added to the dataset.
