### ISSUE TITLE
Add an MP: Chris Pincher

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#15]
### Name of the MP

Chris Pincher

### What is the MPs political party?

Conservative

### Constituency

Tamworth

### Name of source

Pink News

### URL of source

https://www.thepinknews.com/2024/07/03/lgbtq-representation-house-of-commons-general-election/

### Explanation of source

Chris Pincher needs to be added to these various Parliaments:

https://mps.whoare.lgbt/historic/parliament/start/2019-12-13

https://mps.whoare.lgbt/historic/parliament/end/2019-11-06

https://mps.whoare.lgbt/historic/parliament/start/2017-06-21

https://mps.whoare.lgbt/historic/parliament/end/2017-05-03

**Comment by johnpeart** [comment]
Thanks for pointing this out.

If I recall correctly this was someone who has come up before; I took the decision to _not_ include Chris Pincher on account of the fact that he was 'outed' rather than 'came out'. There are a number of MPs in recent years that have been the subject of allegations and stories that would _indicate_ they are LGBT, but they themselves haven't then confirmed or denied it.

I'd be interested in your views on this and whether you feel there is sufficient public evidence of his sexual orientation; or whether you think this position is justifiable.

**Comment by HereAgain2024** [comment]
I think we should add both Chris Pincher and Patrick Grady. 

Pincher was openly gay and at one point was a Patron of LGBT Conservatives. The National Herald refers to Patrick Grady as a gay man in 2022: https://www.heraldscotland.com/politics/20236731.mark-smith-patrick-grady-scandal-sign-changed/ so looks like he was openly gay as well.

Technically they were both outed as gay, even though they were open, due to scandals and whilst their political careers ended in disgrace they are still LGBT+ MPs, same as Imran Ahmad Khan or David Law, who were of course outed due to their own scandals.

**Comment by HereAgain2024** [comment]
I think we should add both Chris Pincher and Patrick Grady.

Pincher was openly gay and at one point was a Patron of LGBT Conservatives.
The National Herald refers to Patrick Grady as a gay man in 2022:
https://www.heraldscotland.com/politics/20236731.mark-smith-patrick-grady-scandal-sign-changed/
so looks like he was openly gay as well.

Technically they were both outed as gay, even though they were open, due to
scandals and whilst their political careers ended in disgrace they are
still LGBT+ MPs, same as Imran Ahmad Khan or David Law, who were of course
outed due to their own scandals.

Cheers!

**Comment by HereAgain2024** [comment]
Hey,

Have you decided about adding both Chris and Patrick to the database? Personally I still think you should!

**Comment by johnpeart** [comment]
Hello!

Sorry for the delay. Busy at work, and then I wanted to look at improving some of the underlying infrastructure of the website post election which slipped this off my list!

The dataset has now been updated to include both the MPs you suggest. Thanks for prompting me to reconsider these two.
