### ISSUE TITLE
Add an MP: Patrick Grady

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#16]
### Name of the MP

Patrick Grady

### What is the MPs political party?

Scottish National

### Constituency

Glasgow North

### Name of source

Pink News

### URL of source

https://www.thepinknews.com/2024/07/03/lgbtq-representation-house-of-commons-general-election/

### Explanation of source

Patrick Grady needs to be added to these various Parliaments:

https://mps.whoare.lgbt/historic/parliament/end/2024-05-30

https://mps.whoare.lgbt/historic/parliament/start/2019-12-13

https://mps.whoare.lgbt/historic/parliament/end/2019-11-06

https://mps.whoare.lgbt/historic/parliament/start/2017-06-21

https://mps.whoare.lgbt/historic/parliament/end/2017-05-03

**Comment by johnpeart** [comment]
Thanks. 

This MP is similar to Chris Pincher (see comment on #15). 

Grateful for your thoughts on that.

**Comment by johnpeart** [comment]
Added Patrick Grady to the dataset in 1ffd6d612c5e2b3914cf13bd332ac43832b8b04b
