### ISSUE TITLE
Add an MP: Ben Maguire

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#17]
### Name of the MP

Ben Maguire

### What is the MPs political party?

Liberal Democrat

### Constituency

North Cornwall

### Name of source

Falmouth Packet

### URL of source

https://www.falmouthpacket.co.uk/news/24433442.cornwalls-losing-conservative-mps-commented-defeats/

### Explanation of source

Ben Maguire has a husband

**Comment by johnpeart** [comment]
Thanks.

This will be updated momentarily.
