### ISSUE TITLE
Add an MP: Tris Osborne

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#18]
### Name of the MP

Tris Osborne

### What is the MPs political party?

Labour

### Constituency

Chatham and Aylesford

### Name of source

The Northern Echo

### URL of source

https://www.thenorthernecho.co.uk/news/7000203.gay-rights-campaigners-stage-same-sex-weddings/

### Explanation of source

Tris Osborne is openly gay

**Comment by johnpeart** [comment]
Thanks.

I'll add to the dataset shortly.
