### ISSUE TITLE
Add an MP: Kevin McKenna

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#19]
### Name of the MP

Kevin McKenna

### What is the MPs political party?

Labour

### Constituency

Sittingbourne and Sheppey

### Name of source

Twitter

### URL of source

https://x.com/KMcKLabour/status/1810017758454632884

### Explanation of source

Kevin McKenna has a husband

**Comment by johnpeart** [comment]
Thank you.

Up to date now!
