### ISSUE TITLE
Add an MP: Peter Swallow

### ISSUE THREAD

**Issue by JolanOne** [johnpeart/lgbt-mp#23]
### Name of the MP

Peter swallow

### What is the MPs political party?

Labour

### Constituency

Bracknell

### Parliamentary website

https://members.parliament.uk/member/5165/contact

### Name of source

Twitter

### URL of source

https://x.com/rishi175/status/1808974532650414513?t=2mYiX8Rbj5EzJQ06OVprbA&s=19

### Explanation of source

This is a post from the MPs partner who is of the same gender as the MP.

**Comment by johnpeart** [comment]
Thank you for sharing this. It's now been added to the dataset.

I think I'm right in saying this addition also means there are now more LGBT+ MPs in the current Parliament than there were in the last one!
