### ISSUE TITLE
Add an MP: Martin Rhodes

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#24]
### Name of the MP

Martin Rhodes

### What is the MPs political party?

Labour

### Constituency

Glasgow North

### Name of source

LGBT+ Labour Scotland

### URL of source

https://lgbtlabourscotland.laboursites.org/2010/05/05/councillor-martin-rhodes/

### Explanation of source

Openly LGBT+

**Comment by johnpeart** [comment]
Thanks for flagging.

I don't think the source can constitute Martin being openly LGBT+; the source says he is the honorary president and that he is a "champion" for LGBT+ people. That doesn't mean he is in LGBT+.

I've done some further searches for any other sources that might be relevant and contain some kind of open statement from Martin. Unfortunately I can't find any at the moment. If he is LGBT+, I suspect that it will come up in public domain information or contributions in parliament in due course.

I will leave this addition 'open' for now, pending further information.

**Comment by HereAgain2024** [comment]
I've found a video from 4 years ago where he is stated to be the President of LGBT+ Labour Scotland: https://www.facebook.com/watch/?v=294925735250029. 

I've found the up to date version of the LGBT+ Labour Commitee and all of the Honorary Presidents are all openly LGBT+, so I would be surprised if Martin Rhodes would have been made an honorary president, having served as president, if he wasn't openly LGBT+: https://lgbtlabourscotland.laboursites.org/category/the-committee/
