### ISSUE TITLE
Add an MP: Multiple MPs in 2010 - 2015 Parliament

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#28]
### Name of the MP

Alan Duncan

### What is the MPs political party?

Conservative

### Constituency

N/A

### Name of source

Online

### URL of source

Online

### Explanation of source

Add all of the below to the 2010 section:

* Alan Duncan
* Nigel Evans
* Michael Fabricant
* Crispin Blunt
* Nick Gibb
* Greg Barker

Labour:

* Nick Brown
* Clive Betts
* Angela Eagle
* Ben Bradshaw
* Gordon Marsden
* Stephen Twigg
* Shaun Woodward
* Chris Bryant
* David Cairns

Lib Dems

* Simon Hughes
* David Laws
* Steve Gilbert

**Comment by johnpeart** [comment]
Hello again.

I think there's a bug in the code that shows the MPs on the historical parliaments.

The [underlying list](https://github.com/johnpeart/lgbt-mp/blob/main/_data/members.csv) has those MPs listed correctly, but they aren't showing on the [2010 page](https://www.lgbt.mp/parliament/start/2010-05-18/) or the [2015 page](https://www.lgbt.mp/parliament/end/2015-03-30/).

Other pages seem to be working correctly.

I'll look into this further as a bug on the site, but this issue can be closed as the dataset is already up-to-date.

**Comment by johnpeart** [comment]
This issue should now be resolved.

I double checked your list above and I had missed a couple of people! Thanks for spotting that. I've added those into the dataset.
