### ISSUE TITLE
Matt Turmaine

### ISSUE THREAD

**Issue by matt-watford** [johnpeart/lgbt-mp#33]
### Name of the MP

Matt Turmaine

### What is the MPs political party?

Labour

### Constituency

Watford

### Parliamentary website

https://members.parliament.uk/member/5130/contact

### Name of source

Matt Turmaine

### URL of source

Self-declared by MP.

**Comment by johnpeart** [comment]
Thank you Matt.

I have now updated the dataset to include this information.
