### ISSUE TITLE
Alex Barros-Curtis

### ISSUE THREAD

**Issue by miamartini** [johnpeart/lgbt-mp#34]
### Name of the MP

Alex Barros-Curtis

### What is the MPs political party?

Labour

### Constituency

Cardiff West

### Parliamentary website

https://members.parliament.uk/member/5175/contact

### Name of source

ITV News

### URL of source

https://www.itv.com/news/wales/2024-07-24/meet-abc-the-new-welsh-labour-mp-for-cardiff-west

### Explanation of source

Alex Barros-Curtis confirmed that he is gay and has a husband

**Comment by johnpeart** [comment]
Thank you Mia. This has been added to the dataset.
