### ISSUE TITLE
Add an MP: Alex Barros-Curtis

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#36]
### Name of the MP

Alex Barros-Curtis

### What is the MPs political party?

Labour

### Constituency

Cardiff West

### Name of source

ITV

### URL of source

https://www.itv.com/news/wales/2024-07-24/meet-abc-the-new-welsh-labour-mp-for-cardiff-west

### Explanation of source

Openly gay and has a husband

**Comment by johnpeart** [comment]
Linked to #34.

**Comment by johnpeart** [comment]
Thank you.

This has now been added to the dataset.
