### ISSUE TITLE
Add an MP: Matt Turmaine

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#37]
### Name of the MP

Matt Turmaine

### What is the MPs political party?

Labour

### Constituency

Watford

### Name of source

LGBT+ Labour 

### URL of source

https://www.lgbtlabour.org.uk/campaign_session_in_watford

### Explanation of source

Openly LGBT+

**Comment by johnpeart** [comment]
Thank you.

The MP themselves appears to have also reached out in parallel. I have updated the dataset.
