### ISSUE TITLE
Add an MP: Martin Rhodes

### ISSUE THREAD

**Issue by miamartini** [johnpeart/lgbt-mp#39]
### Name of the MP

Martin Rhodes

### What is the MPs political party?

Labour

### Constituency

Glasgow North

### Parliamentary website

https://members.parliament.uk/member/5251/contact

### Name of source

Twitter

### URL of source

https://twitter.com/JamesAsser/status/1859719790413349332

### Explanation of source

Martin Rhodes appears in photo of LGBT Labour MPs

**Comment by johnpeart** [comment]
Link to #24
