### ISSUE TITLE
Kieran Mullan

### ISSUE THREAD

**Issue by Frobsi** [johnpeart/lgbt-mp#5]
### Name of the MP

Dr Kieran Mullan

### What is the MPs political party?

Conservative

### Constituency

Bexhill and Battle 

### Parliamentary website

https://members.parliament.uk/member/4860/contact

### Name of source

MPs Who Are LGBT

### URL of source

https://mps.whoare.lgbt/historic/parliament/end/2024-05-30

### Explanation of source

It’s your own website. Dr Mullan just changed seats in this election.

**Comment by johnpeart** [comment]
Thank you for spotting!

I will update this later today.
