### ISSUE TITLE
Add an MP: Tom Gordon

### ISSUE THREAD

**Issue by emynx** [johnpeart/lgbt-mp#6]
### Name of the MP

Tom Gordon

### What is the MPs political party?

Liberal Democrat

### Constituency

Harrogate & Knaresborough

### Parliamentary website

https://members.parliament.uk/member/5032/contact

### Name of source

Twitter

### URL of source

https://x.com/tomgordonLD/status/1239840883303944192

### Explanation of source

This statement comes directly from the MP.

**Comment by johnpeart** [comment]
Thank you.

I will add Tom to the dataset later today.
