### ISSUE TITLE
Add an MP: Tom Gordon

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#7]
### Name of the MP

Tom Gordon

### What is the MPs political party?

Liberal Democrat

### Constituency

Harrogate and Knaresborough

### Name of source

Pink News

### URL of source

https://www.thepinknews.com/2024/07/05/lgbtq-mps-general-election/#page/6

### Explanation of source

According the UK LGBT Website Pink News, he is openly LGBT+

**Comment by johnpeart** [comment]
Thank you. 

The dataset will be updated shortly to include Tom Gordon. Another contributor has also identified a public statement by Tom, identifying himself as a gay man.
