### ISSUE TITLE
Add an MP: Sarah Dyke

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#8]
### Name of the MP

Sarah Dyke

### What is the MPs political party?

Liberal Democrat

### Constituency

Glastonbury and Somerton

### Name of source

Pink News

### URL of source

https://www.thepinknews.com/2024/07/05/lgbtq-mps-general-election/#page/6

### Explanation of source

According the UK LGBT Website Pink News, she is openly LGBT+

**Comment by johnpeart** [comment]
Thank you.

I will add Sarah to the dataset later today (and thank you for highlighting her previously – I'm glad there is now a reliable source we can rely on; Andrew Reynolds (the author of that article) does a lot of work as an academic in this field).
