### ISSUE TITLE
Add an MP: Blake Stephenson

### ISSUE THREAD

**Issue by HereAgain2024** [johnpeart/lgbt-mp#9]
### Name of the MP

Blake Stephenson

### What is the MPs political party?

Conservative

### Constituency

Mid Bedfordshire

### Name of source

Pink News

### URL of source

https://www.thepinknews.com/2024/07/05/lgbtq-mps-general-election/#page/6

### Explanation of source

According the UK LGBT Website Pink News, he is openly LGBT+

**Comment by johnpeart** [comment]
Thank you.

I will add Blake to the dataset today.
